### ISSUE TITLE
build fails when selecting serde feature but not std feature

### ISSUE THREAD

**Issue by tspiteri** [starkat99/half-rs#79]
Build fails with this dependency setting:
```toml
[dependencies.half]
version = "2"
default-features = false
features = ["serde"]
```

Adding the `"std"` feature makes the build work.
```toml
[dependencies.half]
version = "2"
default-features = false
features = ["serde", "std"]
```

**Comment by tspiteri** [comment]
There are two possible solutions I can think of:

1. Make the serde feature depend on the std feature. With rust 1.60 this would be simple; just add a new feature  in Cargo.toml:

    ```toml
    [features]
    serde = ["dep:serde", "std"]
    ```

    But with earlier rust I didn't manage to get it to work. I tried to import `serde` with a different name e.g.

    ```toml
    [dependencies]
    serde_crate = { package = "serde", version = "1.0" ... }
    ```
    
    and then use `serde_crate` instead of `serde` in the code, or add

    ```rust
    #[cfg(feature = "serde")]
    extern crate serde_crate as serde;
    ```

    but that broke `derive(Serialize)`. Maybe a manual implementation could replace the derive, or there's another fix, but I am completely unfamiliar with serde's derives.

2. Otherwise features that are now gated with `#[cfg(feature = "serde")]` could be gated with `#[cfg(all(feature = "serde", feature = "std"))]` instead.

(Some serde stuff just depends on `alloc` not on `std`.)
